export const sectionListArray = [
    {viewValue: 'Arts', value: 'arts'},
    {viewValue: 'Automobiles', value: 'automobiles'},
    {viewValue: 'Books', value: 'books'},
    {viewValue: 'Business', value: 'business'},
    {viewValue: 'Fashion', value: 'fashion'},
    {viewValue: 'Food', value: 'food'},
    {viewValue: 'Health', value: 'health'},
    {viewValue: 'Home', value: 'home'},
    {viewValue: 'Insider', value: 'insider'},
    {viewValue: 'Magazine', value: 'magazine'},
    {viewValue: 'Movies', value: 'movies'},
    {viewValue: 'NY Region', value: 'nyregion'},
    {viewValue: 'Obituaries', value: 'obituaries'},
    {viewValue: 'Opinion', value: 'opinion'},
    {viewValue: 'Politics', value: 'politics'},
    {viewValue: 'Realestate', value: 'realestate'},
    {viewValue: 'Science', value: 'science'},
    {viewValue: 'Sports', value: 'sports'},
    {viewValue: 'sundayreview', value: 'sundayreview'},
    {viewValue: 'Technology', value: 'technology'},
    {viewValue: 'Theater', value: 'theater'},
    {viewValue: 'T-magazine', value: 't-magazine'},
    {viewValue: 'Travel', value: 'travel'},
    {viewValue: 'Upshot', value: 'upshot'},
    {viewValue: 'US', value: 'us'},
    {viewValue: 'World', value: 'world'}
]